name: 'Stage: rollback'

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  rollback-stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rollback application in stage
        run: |
          echo "Rolling back application in stage"
          echo "Rolling back to previous tag"
          echo "Rollback complete"